### ISSUE TITLE
/info 엔드포인트 변경 건의

### ISSUE THREAD

**Issue by seorinnn** [kakao-tech-campus-2nd-step3/Team4_FE#34]
### /info 엔드포인트 변경 건의

기획 단계에서 `User API`의 `/info` 에서 주고받는 정보는 키, 몸무게, 인바디이미지 3가지였음.
하지만 현재는 키와 몸무게가 삭제되어 `inbodyImage`만 주고받는 상황임.

그러므로 `/info`엔드포인트를 `/inbody` 로 변경하는 것에 대한 건의

**Comment by noojmogstel** [comment]
유저정보에 추가될 정보가 있을거라고 생각하면 (현재는 PT라는 SportsType에만 초점이 맞춰져있지만, 추후 여러 운동들을 추가했을때) 추가되는 정보를 신체정보 테이블에 추가해서 같이 관리하게 될것 같은데 그렇다면,  `/info` 로 하는것이 좋을것같습니다.

**Comment by chris0825** [comment]
/info 엔드 포인트의 경우 추후 개발 예정인 (일반, 트레이너)회원의 내 정보 수정 기능의 API와 혼용 될 가능성이 있다고 판단됨.
따라서, 현재 Issue로 건의된 /info의 엔드 포인트는 /bodyInfo로 변경하고 추후 개발될 내 정보 수정 기능의 엔드 포인트를 /info로 사용하기로 결정.

**Comment by chris0825** [comment]
/info 엔드 포인트의 경우 추후 개발 예정인 (일반, 트레이너)회원의 내 정보 수정 기능의 API와 혼용 될 가능성이 있다고 판단됨.
따라서, 현재 Issue로 건의된 /info의 엔드 포인트는 /bodyInfo로 변경하고 추후 개발될 내 정보 수정 기능의 엔드 포인트를 /info로 사용하기로 결정.
